# Maven
# This pipeline will build the java selenium test project, and run its tests. 
# The tests to run can be re-configured if a user specifies a value for the  
# Tests To Run parameter as per:  
# https://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html 
# If TestsToRun is left unfilled, all tests will run. Otherwise only matching tests will run. 

trigger:
- master

pool:
  vmImage: internet

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
